config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :staffs
  resources :coordinators
  resources :administratives
  devise_for :users
  resources :events
  resources :tickets
  root "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets
  paginates_per 10
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.page(params[:page])
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @tickets = Ticket.where(event_id: params[:id]).order(:id)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'events/tickets_list', pdf: 'tickets_list'}
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        CreateMultipleTicketsJob.perform_later(@event, tickets_url)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      authorize @event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name,
                                    :description,
                                    :place,
                                    :event_datetime,
                                    :capacity,
                                    :seats_taken
      )
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%- if policy(event).can_see? %>
  <div class="container">
    <%= form_with(model: event, local: true) do |form| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, id: :event_name, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description, id: :event_description, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :place %>
        <%= form.text_field :place, id: :event_place, class: 'form-control' %>
      </div>

      <div class="field date-field">
        <%= form.label :event_datetime %>
        <%= form.datetime_select :event_datetime, id: :event_event_datetime, html: { class: 'form-control' } %>
      </div>

      <div class="field">
        <%= form.label :capacity %>
        <%= form.number_field :capacity, id: :event_capacity, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :seats_taken %>
        <%= form.number_field :seats_taken, id: :event_seats_taken, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit "Save", class: 'btn btn-success' if policy(event).can_see? %>
      </div>
    <% end %>
  </div>
<%- else %>
<div class="text-center alert alert-error"> YOU ARE NOT ALLOWED TO PERFORM THIS ACTION</div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <h1>Editing Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Show', @event %> |
  <%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Events</h1>
  <%= paginate @events %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Place</th>
        <th>Event datetime</th>
        <th>Capacity</th>
        <th>Seats taken</th>
        <th colspan="3">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= link_to event.name, event_url(event.id) %></td>
          <td><%= event.place %></td>
          <td><%= datetime_format(event.event_datetime) %></td>
          <td><%= event.capacity %></td>
          <td><%= event.seats_taken %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @events %>
  <br>

  <%= link_to 'New Event', new_event_path, class: 'btn btn-success' %>
</div>

app/views/events/new.html.erb
<div class="container">
  <h1>New Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= @event.place %>
  </p>

  <p>
    <strong>Event datetime:</strong>
    <%= datetime_format(@event.event_datetime) %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= @event.capacity %>
  </p>

  <p>
    <strong>Seats taken:</strong>
    <%= @event.seats_taken %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= @event.available %>
  </p>

  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Back', events_path %>

  <p>
    <strong>QR codes:</strong>
  </p>

  <% if @tickets %>
    <% @tickets.each do |ticket| %>
      <div class="card qr-code">
          <%= ticket.qr_code&.html_safe || 'Genetating QR code' %>
        <div class="card-block">
          <h4 class="card-title"><%= ticket.code %></h4>
          <strong>Event:</strong>
          <%= @event.name %>
          <br/>
          <strong>Description:</strong>
          <%= @event.description %>
          <br/>
          <strong>Place:</strong>
          <%= @event.place %>
          <br/>
          <strong>Event datetime:</strong>
          <br/>
          <%= datetime_format(@event.event_datetime) %>
          <a href="#" class="btn btn-primary">Go to ticket</a>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>Tickets are being generated, wait a momment and refresh this page</p>
  <% end %>
</div>

app/views/events/tickets_list.pdf.erb
<!DOCTYPE html>
<head>
  <title>Tickets</title>
  <meta name="author" content="Neuville11">
  <%= wicked_pdf_stylesheet_link_tag 'tickets'%>
</head>
<body>
  <p>
    <strong>Event:</strong>
    <%= @event.name %>
    <br/>
    <strong>Description:</strong>
    <%= @event.description %>
    <br/>
    <strong>Place:</strong>
    <%= @event.place %>
    <br/>
    <strong>Event datetime:</strong>
    <%= datetime_format(@event.event_datetime) %>
  </p>

  <% if @tickets %>
    <% @tickets.each do |ticket| %>
      <div class="card qr-code">
          <%= ticket.qr_code&.html_safe || 'Genetating QR code' %>
        <div class="card-block">
          <h4 class="card-title"><%= ticket.code %></h4>
          <strong>Event:</strong>
          <%= @event.name %>
          <br/>
          <strong>Description:</strong>
          <%= @event.description %>
          <br/>
          <strong>Place:</strong>
          <%= @event.place %>
          <br/>
          <strong>Event datetime:</strong>
          <br/>
          <%= datetime_format(@event.event_datetime) %>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>Tickets are being generated, wait a momment and refresh this page</p>
  <% end %>
</body>
</html>