config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :staffs
  resources :coordinators
  resources :administratives
  devise_for :users
  resources :events
  resources :tickets
  root "events#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :event
  paginates_per 25

  STATUS = [
    'Pending',
    'Checked'
  ]
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all.page(params[:page])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find_by(code: params[:id])
    @event = Event.find(@ticket.event_id)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find_by(code: params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    @ticket = Ticket.find_by(id: params[:id])
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket.code), notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket.code }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find_by(code: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(
        :event_id,
        :code,
        :ticket_url,
        :seat_number,
        :status
      )
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<div class="container">
  <%= form_with(model: ticket, local: true) do |form| %>
    <% if ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%- if request_action == 'new' %>
      <div class="field col-md-4">
        <%= form.label :event_id %>
        <%= form.collection_select :event_id, Event.all, :id, :name, {}, class: 'form-control' %>
      </div>

      <div class="field col-md-12">
        <%= form.label :code %>
        <%= form.text_field :code, id: :ticket_code, class: 'form-control' %>
      </div>

      <div class="field col-md-12">
        <%= form.label :ticket_url %>
        <%= form.text_field :ticket_url, id: :ticket_ticket_url, class: 'form-control' %>
      </div>
    <% end %>

    <div class="field col-md-2">
      <%= form.label :seat_number %>
      <%= form.text_field :seat_number, id: :ticket_seat_number, class: 'form-control' %>
    </div>
    <div class="field col-md-12">
      <%= form.label :status %>
      <%= form.select :status, Ticket::STATUS, {}, class: 'form-control' %>
    </div>

    <div class="field col-md-12">
      <%= form.submit 'Submit', class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/tickets/edit.html.erb
<div class="container">
  <h1>Editing Ticket</h1>

  <%= render 'form', ticket: @ticket %>

  <%= link_to 'Show', ticket_url(@ticket.code) %> |
  <%= link_to 'Back', tickets_path %>
</div>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Tickets</h1>
  <%= paginate @tickets %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Event</th>
        <th>Code</th>
        <th>Ticket url</th>
        <th>Seat number</th>
        <th>Status</th>
        <th colspan="3">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= link_to Event.find(ticket.event_id).name, event_url(ticket.event_id) %></td>
          <td><%= ticket.code %></td>
          <td><%= ticket.ticket_url %></td>
          <td><%= 'not assigned' if (ticket.seat_number || '') %></td>
          <td><%= ticket.status %></td>
          <td><%= link_to 'Show', ticket_url(ticket.code) %></td>
          <td><%= link_to 'Edit', edit_ticket_path(ticket.code) %></td>
          <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @tickets %>

  <br>

  <%= link_to 'New Ticket', new_ticket_path, class: 'btn btn-success' %>
</div>

app/views/tickets/new.html.erb
<div class="container">
  <h1>New Ticket</h1>

  <%= render 'form', ticket: @ticket %>

  <%= link_to 'Back', tickets_path %>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <p>
    <strong>Event:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= @event.place %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= datetime_format(@event.event_datetime) %>
  </p>

  <p>
    <strong>Ticket url:</strong>
    <%= @ticket.ticket_url %>
  </p>

  <p>
    <strong>Seat number:</strong>
    <%= 'not assigned' if (@ticket.seat_number || '') %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @ticket.status || 'pending' %>
  </p>

  <div>
    <%= link_to 'Edit', edit_ticket_path(@ticket.code), class: 'btn btn-success' %> |
    <%= link_to 'Back', tickets_path, class: 'btn btn-primary' %>
  </div>

  <p><strong>QR code:</strong></p>

  <div class="qr-code">
    <%= @ticket.qr_code.html_safe %>
    <%= @ticket.code %>
  </div>
</div>